name: Project 2 Only

on:
  push:
    branches: [ "main" ]
    paths: 
      - "project2/**"
    

env:
  PROJECT_ID: test
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  project2:
    name: Project2 Job
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: list files
        run: ls ./project2
