name: Project 1 Only

on:
  push:
    branches: [ "main" ]
    paths: 
      - "project1/**"
    

env:
  PROJECT_ID: test
  GITHUB_SHA: ${{ github.sha }}
  GITHUB_REF: ${{ github.ref }}

jobs:
  project1:
    name: Project1 Job
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: list files
        run: ls ./project1
